### ISSUE TITLE
Red Flag PR's from Problem Contributors

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#113]
> ["nevermind then, this is way too much bullshit for me to go through."](https://github.com/monero-project/kovri/pull/81)

> ```
2016-01-25 19:47:50     +psi    hue
2016-01-25 19:47:59     +psi    have fun killing your project kid
2016-01-25 19:47:59     <--     psi (jeff@nr4nbmyavwetylqwo6x6ibyoourtn477iwcpb25gapzuko6s4ena.b32.i2p) has left #kovri-dev (leaving)
```

> ```
2016-01-29 11:09:59     +psi    no more PR are coming from me, I am taking this project in the correct direction without anonimal
2016-01-29 11:10:27     +psi    have fun with your toy
```

Yet, here we have another [PR](https://github.com/monero-project/kovri/pull/112) from psi (a.k.a., @majestrate)

Contributors like this should be red flagged as they have the knowledge-set and capacity cause malicious intent and at times have provided [questionable code](https://github.com/majestrate/kovri/commit/3829173fd5c770cff318a36c5064f9d9cdce1abc#diff-02d8058153d632e91662f70333f6713c) with security implications.

The only enforceable consequence that we can currently afford is to label PRs from problem contributors with a label of ```red-flag``` and then have **all mergers review PRs from any red-flagged contributors before merging** and, regardless of its quality, merge - but respond quickly either by reverting or patching when appropriate.

In addition, as described in our guide, PRs to master should be closed and contributor asked to PR to development as to avoid huge disasters.

There have been a multitude of issues with this contributor's work, as is clearly documented in the "closed pull requests" section, so this proposal is not unwarranted nor is it unsupported by empirical evidence. 

We are writing anonymity software that put people's lives are on the line - so quality assurance is paramount. If this were most other software, I wouldn't bother writing up a proposal like this - but here we are.

**Comment by EinMByte** [comment]
The code in the above mentioned PR was not questionable. Tests are unlikely to cause major security issues. Hence I merged it and made a few stylistic modifications afterwards (see development branch).

The only mistake was merging into master, but this should be no problem as soon as development is merged into master again.

**Comment by majestrate** [comment]
> There have been a multitude of issues with this contributor's work, as is clearly documented in the "closed pull requests" section, so this proposal is not unwarranted nor is it unsupported by empirical evidence.

Citation Required.

> Contributors like this should be red flagged as they have the knowledge-set and capacity cause malicious intent and at times have provided questionable code with security implications.

This is pointless drama.

**Comment by anonimal** [comment]
We're putting the idea aside for now but will resurrect the issue in the future should problems persist.
